# Generated by Django 5.2.9 on 2026-02-05 05:30

import lectorqr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectorqr', '0003_refactor_alumno_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=lectorqr.fields.EncryptedTextField(blank=True, null=True, verbose_name='Teléfono'),
        ),
    ]
